// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTD3Gac2M4pR3LupSrqMN4W4nNRiw4g68',
    appId: '1:1064961390890:web:a18958bb2786be1ff2c653',
    messagingSenderId: '1064961390890',
    projectId: 'test-256a3',
    authDomain: 'test-256a3.firebaseapp.com',
    storageBucket: 'test-256a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKMmb_rAIgL30kGmkLBgSU5Rdv99rht0M',
    appId: '1:1064961390890:android:2cc7dc4727317940f2c653',
    messagingSenderId: '1064961390890',
    projectId: 'test-256a3',
    storageBucket: 'test-256a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfl_cJtjhQN5T8gjpWLfRtq9yUQDkEbtk',
    appId: '1:1064961390890:ios:6c48537b1ec767fef2c653',
    messagingSenderId: '1064961390890',
    projectId: 'test-256a3',
    storageBucket: 'test-256a3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfl_cJtjhQN5T8gjpWLfRtq9yUQDkEbtk',
    appId: '1:1064961390890:ios:6c48537b1ec767fef2c653',
    messagingSenderId: '1064961390890',
    projectId: 'test-256a3',
    storageBucket: 'test-256a3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTD3Gac2M4pR3LupSrqMN4W4nNRiw4g68',
    appId: '1:1064961390890:web:3ca4d639152a7ec6f2c653',
    messagingSenderId: '1064961390890',
    projectId: 'test-256a3',
    authDomain: 'test-256a3.firebaseapp.com',
    storageBucket: 'test-256a3.firebasestorage.app',
  );
}
